project:
  type: website
  output-dir: docs

website:
  title: "Gapminder Analysis"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: life-gdp.qmd
        text: "Life Expectancy & GDP"
      - href: life-population.qmd
        text: "Life Expectancy & Population"
      - href: country.qmd
        text: "Basic Analysis"
format:
  html:
    theme: default  
    toc: true




